### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by infeeeee** [nielsfaber/scheduler-card#119]
I updated Hungarian translation, and I want to test it in my HA install.

I run a simple `npm i` but it seems it's not enough, I get errors on `npm run build`, I guess some globally installed modules are needed as well?

**Comment by nielsfaber** [comment]
`npm install` followed by `npm start` should do the job.
If dependencies are not set up correctly in `package.json` then let me know.

**Comment by infeeeee** [comment]
```
C:\Users\username\Documents\_git\scheduler-card>npm start

> scheduler-card@1.0.0 start C:\Users\username\Documents\_git\scheduler-card
> rollup -c --watch

[!] Error: No valid exports main found for 'C:\Users\username\Documents\_git\scheduler-card\node_modules\@rollup\pluginutils'
Error: No valid exports main found for 'C:\Users\username\Documents\_git\scheduler-card\node_modules\@rollup\pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\username\Documents\_git\scheduler-card\node_modules\@rollup\plugin-json\dist\index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scheduler-card@1.0.0 start: `rollup -c --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scheduler-card@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-10-09T09_32_51_676Z-debug.log

```

```
C:\Users\username\Documents\_git\scheduler-card>npm run build

> scheduler-card@1.0.0 build C:\Users\username\Documents\_git\scheduler-card
> npm run lint && npm run rollup && npm run babel


> scheduler-card@1.0.0 lint C:\Users\username\Documents\_git\scheduler-card
> eslint src/*.ts

YAMLException: end of the stream or a document separator is expected in "C:\Users\username\Documents\_git\scheduler-card\.prettierrc" at line 2, column 9:
        semi: true,
            ^
Occurred while linting C:\Users\username\Documents\_git\scheduler-card\src\action-handler-directive.ts:1
    at generateError (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:1809:10)
    at throwError (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:1813:9)
    at readDocument (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:3203:5)
    at loadDocuments (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:3241:5)
    at load (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:3262:19)
    at Object.safeLoad (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:3287:10)
    at loadYaml (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:4302:19)
    at Explorer.loadFileContent (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:4733:14)
    at Explorer.createCosmiconfigResultSync (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:4769:31)
    at Explorer.loadSearchPlaceSync (C:\Users\username\Documents\_git\scheduler-card\node_modules\prettier\third-party.js:4660:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scheduler-card@1.0.0 lint: `eslint src/*.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the scheduler-card@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-10-09T09_30_37_238Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! scheduler-card@1.0.0 build: `npm run lint && npm run rollup && npm run babel`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the scheduler-card@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2020-10-09T09_30_37_290Z-debug.log
```

```
C:\Users\username\Documents\_git\scheduler-card>node -v
v13.6.0
```

**Comment by nielsfaber** [comment]
I don't know. Not really looking for debugging this right now.
If you send in a pull request with the updated language, i will include it in the next release. It's ok for me if changes are needed afterwards.

**Comment by infeeeee** [comment]
I think I should have to `npm i -g eslint` or something like that, package.json can't contain global dependencies. But I'm not familiar with typescript development, it seemed easier to ask. I opened a PR with translation update, I will leave this open, I think it would help new contributors if exact build instructions would be added.

**Comment by nielsfaber** [comment]
I don’t want to be rude in any way.
It’s just that I don’t know how this works either.
I basically copied the config files from another card, and getting it to run was a bit trial and error for me too.
Typescript is a new thing for me as well honestly. But once it works all is fine.
Linting gives me plenty of errors also, I decided to stay away from it.
Rollup is what I use.
Anyway, I don’t mind if PRs need to be revised later, so you don’t have to go through this trouble.
