### ISSUE TITLE
Can't create any new schedules after update to HA 2021.1.5

### ISSUE THREAD

**Issue by CaCu15** [nielsfaber/scheduler-card#318]
Hello Niels,

first I would like to thank you for your great scheduler implementation. I'm using it to control my climate schedule and it worked great so far. Today I updated to the most recent versions of HA, Scheduler Integration and Scheduler Card:
- Home Assistant 2021.1.5 as Docker Container (not HASS)
- Scheduler Integration: V 3.03 
- Scheduler Card: V 2.05

After the update I can't create any schedules and all the old schedules are deleted. If I try to create a new schedule I keep getting the following error message: `"Error in call to scheduler/add.  extra keys not allowed @ data['entries']" `, see screenshot below:

![grafik](https://user-images.githubusercontent.com/34535696/105629109-5a8ce380-5e41-11eb-944f-446aff70d141.png)

The HA log contains a similar error message:

```
2021-01-24 12:20:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140369606040208] extra keys not allowed @ data['entries']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1399, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['entries']
```

I tried to remove both scheduler components completely, re-started HA and re-installed both components. But that didn'd help. Any help would be greatly appreciated.

Regards, Carsten

**Comment by nielsfaber** [comment]
The error suggests that your scheduler-card is not at V2.0.5.
Please refresh your browser (cache) and see here: https://github.com/nielsfaber/scheduler-card#how-do-i-check-which-version-i-am-using

**Comment by CaCu15** [comment]
OK, now I feel stupid. Now it works.  Thx for your quick help.
