### ISSUE TITLE
/config/custom_components/scheduler/switch.py errors in HA log

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/scheduler-card#345]
Just got in HA log - right after Core restart:

2021-03-11 12:42:51 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/scheduler/switch.py", line 754, in async_check_entities_available
    await cb_func()
  File "/config/custom_components/scheduler/switch.py", line 507, in async_handle_device_available
    if self._queued_actions[num]:  # remove state change listener from queue
IndexError: list index out of range

**Comment by mwasowski** [comment]
I have the same for few versions I think.
