### ISSUE TITLE
Unexpected error importing

### ISSUE THREAD

**Issue by roumano** [nielsfaber/scheduler-card#349]
I have install the version v3.0.4 of scheduler-component and scheduler-card V2.0.5 
And i can use it (thanks-you it's do a fantastic job, specially with the combo scheduler-card )

At the start (or restart) of home-assistant, i always got these `Unexpected error importing` issue : 

```
mars 21 21:42:47 rasp hass[5182]: 2021-03-21 21:42:47 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing scheduler/logbook.py
mars 21 21:42:47 rasp hass[5182]: Traceback (most recent call last):
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 21 21:42:47 rasp hass[5182]:     platform = integration.get_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 21 21:42:47 rasp hass[5182]:     cache[full_name] = self._import_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 21 21:42:47 rasp hass[5182]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 21 21:42:47 rasp hass[5182]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 21 21:42:47 rasp hass[5182]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 21 21:42:47 rasp hass[5182]: ModuleNotFoundError: No module named 'custom_components.scheduler-component.logbook'
mars 21 21:42:47 rasp hass[5182]: 2021-03-21 21:42:47 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing scheduler/media_source.py
mars 21 21:42:47 rasp hass[5182]: Traceback (most recent call last):
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 21 21:42:47 rasp hass[5182]:     platform = integration.get_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 21 21:42:47 rasp hass[5182]:     cache[full_name] = self._import_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 21 21:42:47 rasp hass[5182]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 21 21:42:47 rasp hass[5182]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 21 21:42:47 rasp hass[5182]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 21 21:42:47 rasp hass[5182]: ModuleNotFoundError: No module named 'custom_components.scheduler-component.media_source'
mars 21 21:42:47 rasp hass[5182]: 2021-03-21 21:42:47 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing scheduler/group.py
mars 21 21:42:47 rasp hass[5182]: Traceback (most recent call last):
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 21 21:42:47 rasp hass[5182]:     platform = integration.get_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 21 21:42:47 rasp hass[5182]:     cache[full_name] = self._import_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 21 21:42:47 rasp hass[5182]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 21 21:42:47 rasp hass[5182]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 21 21:42:47 rasp hass[5182]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 21 21:42:47 rasp hass[5182]: ModuleNotFoundError: No module named 'custom_components.scheduler-component.group'
mars 21 21:42:47 rasp hass[5182]: 2021-03-21 21:42:47 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing scheduler/system_health.py
mars 21 21:42:47 rasp hass[5182]: Traceback (most recent call last):
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/integration_platform.py", line 30, in _process
mars 21 21:42:47 rasp hass[5182]:     platform = integration.get_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 499, in get_platform
mars 21 21:42:47 rasp hass[5182]:     cache[full_name] = self._import_platform(platform_name)
mars 21 21:42:47 rasp hass[5182]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 504, in _import_platform
mars 21 21:42:47 rasp hass[5182]:     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
mars 21 21:42:47 rasp hass[5182]:   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
mars 21 21:42:47 rasp hass[5182]:     return _bootstrap._gcd_import(name[level:], package, level)
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
mars 21 21:42:47 rasp hass[5182]:   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
mars 21 21:42:47 rasp hass[5182]: ModuleNotFoundError: No module named 'custom_components.scheduler-component.system_health'
```

So, to resume, it's failed to load : 
- scheduler/logbook.py
- scheduler/media_source.py
- scheduler/group.py
- scheduler/system_health.py

Installed by Manual installation on home-assistant Core (Debian OS)

**Comment by nielsfaber** [comment]
> scheduler/logbook.py
scheduler/media_source.py
scheduler/group.py
scheduler/system_health.py

None of these files exist nor have they ever existed.
I have no idea why your HA instance is expecting these files.

**Comment by KTibow** [comment]
It's because they unzipped it to `/config`. Please undo everything you did, and try again with HACS, or putting it in the right place (`/config/custom_components/scheduler`).

**Comment by roumano** [comment]
My bad,
in `custom_components`, i have named it `scheduler-component`
Renamed it to `scheduler` fix these `Unexpected error importing`
