### ISSUE TITLE
Installed the integration but it Failed to set up (scheduler-component v. 3.1.1)

### ISSUE THREAD

**Issue by TheBisk** [nielsfaber/scheduler-card#393]
![image](https://user-images.githubusercontent.com/47088987/117647324-1d98f280-b18d-11eb-9c98-e5ef8e49a660.png)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/scheduler/__init__.py:169
Integration: Scheduler integration (documentation, issues)
First occurred: 12:36:10 PM (1 occurrences)
Last logged: 12:36:10 PM

Error setting up entry Scheduler for scheduler
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/scheduler/__init__.py", line 42, in async_setup_entry
    coordinator = SchedulerCoordinator(hass, session, entry, store)
  File "/config/custom_components/scheduler/__init__.py", line 169, in __init__
    handle_startup()
TypeError: handle_startup() missing 1 required positional argument: '_event'

**Comment by nielsfaber** [comment]
Woops, that looks like a mistake from my side.
You can fix it by doing this: https://github.com/nielsfaber/scheduler-component/commit/50a63bf1e3b0bf9f22c2462fdb56e76d0ac3c905
