### ISSUE TITLE
Disappears from Lovelace after adding a schedule

### ISSUE THREAD

**Issue by Stooovie** [nielsfaber/scheduler-card#440]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
I expect the Schedule to be visible on the Lovelace dashboard, but lately that stopped working. It did work correctly before HA 2021.8.x - I have only noticed it in 2021.8.8 and 2021.9.

### Actual behavior
As soon as I add a new schedule, the Scheduler card disappears from view. It can only be accessed via Lovelace Edit mode. "Show all schedules" is ON and Title of the card is set to "standard". Removing both the Scheduler card and integraion and reinstalling didn't fix the issue.

**Comment by nielsfaber** [comment]
Please check your browser logs for an error message.
Without additional info I cannot help you.

**Comment by cherokee93** [comment]
Here is the config:
```
type: custom:scheduler-card
title: Programmi
include:
  - light
  - switch
  - group
time_step: 5
```

Here is the log:
```
light-entity-card.js:1478 
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at f.trim (light-entity-card.js:1478:27)
    at t.exports (light-entity-card.js:3243:21)
    at c (scheduler-card.js?hacstag=286270157232:179:5035)
    at bs (scheduler-card.js?hacstag=286270157232:179:5091)
    at Fs (scheduler-card.js?hacstag=286270157232:179:23301)
    at scheduler-card.js?hacstag=286270157232:179:22525
    at Array.forEach (<anonymous>)
    at Us (scheduler-card.js?hacstag=286270157232:179:22417)
```
It hangs the page and the only fix is to CTRL+F5

https://user-images.githubusercontent.com/12370126/152188093-f683500c-12c0-4401-9361-8f4e05855187.mp4
