### ISSUE TITLE
Arbitrary schedules not executing

### ISSUE THREAD

**Issue by Strauman** [nielsfaber/scheduler-card#817]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.13

### Bug description

The schedule doesn't run. Python error message from log is attached below.

### Steps to reproduce

I can't find a way to perfectly reproduce, other than make script or automation execution with a schedule and try a few times.

### Additional info

```
Logger: homeassistant.util.logging
Source: util/logging.py:98
First occurred: May 6, 2024 at 20:00:00 (5 occurrences)
Last logged: 08:50:00

Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('51cfe8',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 260, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('e75392',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 260, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('901a7f',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 260, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
Exception in async_timer_finished when dispatching 'scheduler_timer_finished': ('931cda',) Traceback (most recent call last): File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished await self._action_handler.async_queue_actions( File "/config/custom_components/scheduler/actions.py", line 260, in async_queue_actions for queue in self._queues.values(): RuntimeError: dictionary changed size during iteration
```

**Comment by Strauman** [comment]
I see it's fixed in the component update

**Comment by fargiolas** [comment]
I'm on 2024.12.2 and I've been seing this a lot. Schedule misfiring and async_timer_exceptions in the logs:

```
Traceback (most recent call last):
  File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished
    await self._action_handler.async_queue_actions(
        self.schedule[const.ATTR_TIMESLOTS][self._current_slot]
    )
  File "/config/custom_components/scheduler/actions.py", line 256, in async_queue_actions
    for queue in self._queues.values():
                 ~~~~~~~~~~~~~~~~~~~^^
RuntimeError: dictionary changed size during iteration

```

**Comment by fargiolas** [comment]
> I'm on 2024.12.2 and I've been seing this a lot. Schedule misfiring and async_timer_exceptions in the logs:
> 
> ```
> Traceback (most recent call last):
>   File "/config/custom_components/scheduler/switch.py", line 278, in async_timer_finished
>     await self._action_handler.async_queue_actions(
>         self.schedule[const.ATTR_TIMESLOTS][self._current_slot]
>     )
>   File "/config/custom_components/scheduler/actions.py", line 256, in async_queue_actions
>     for queue in self._queues.values():
>                  ~~~~~~~~~~~~~~~~~~~^^
> RuntimeError: dictionary changed size during iteration
> ```

Sorry, ignore me, apparently I was an old version after restoring a backup
