### ISSUE TITLE
Disabling/enabling a scheduler throws an error after upgrading HA to 2024.7

### ISSUE THREAD

**Issue by adrian-bulicanu** [nielsfaber/scheduler-card#823]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v3.2.13

### Component Version

v3.3.4

### Bug description

Disabling/enabling a scheduler changes the slider state but throws the error ```TypeError: object NoneType can't be used in an 'await' expression```.

The logbook shows that the state was changed: ```Schedule XXX turned off, triggered by service Switch: Turn off```.

### Steps to reproduce

1. Open dashboard
2. Tap the slider on the card

### Additional info

Callstack from the log:

```
2024-07-07 09:20:07.039 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140618067713408] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/scheduler/switch.py", line 458, in async_turn_off
    await self.coordinator.async_edit_schedule(
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by Noobalicious** [comment]
The updated scheduler component fixed it for me.  Thanks, Niels!

**Comment by adrian-bulicanu** [comment]
Updating the component version to v3.3.5 fixed the issue. Thanks!
